<?php
class WP_Assessment_Answer_Controller extends WP_REST_Controller {
    public function __construct() { $this->namespace = 'assessment/v1'; $this->rest_base = 'answers'; }
    public function register_routes() { register_rest_route( $this->namespace, '/questions/(?P<id>\\d+)/answers', array( 'methods' => WP_REST_Server::READABLE, 'callback' => array( $this, 'get_items' ), 'permission_callback' => '__return_true' ) ); register_rest_route( $this->namespace, '/answers', array( 'methods' => WP_REST_Server::CREATABLE, 'callback' => array( $this, 'create_item' ), 'permission_callback' => array( $this, 'can_create' ) ) ); register_rest_route( $this->namespace, '/answers/(?P<id>\\d+)', array( array( 'methods' => WP_REST_Server::EDITABLE, 'callback' => array( $this, 'update_item' ), 'permission_callback' => array( $this, 'can_edit' ) ), array( 'methods' => WP_REST_Server::DELETABLE, 'callback' => array( $this, 'delete_item' ), 'permission_callback' => array( $this, 'can_delete' ) ) ) ); }
    private function auth() { return ( new WP_Assessment_JWT_Auth() )->authenticate_request(); } private function manager() { $auth = $this->auth(); return ! is_wp_error( $auth ) && WP_Assessment_Permissions::can_view( 'answer' ); }
    public function can_create() { $auth = $this->auth(); return is_wp_error( $auth ) ? $auth : ( WP_Assessment_Permissions::can_create_answer() ? true : new WP_Error( 'forbidden', 'You do not have permission to create answers.', array( 'status' => 403 ) ) ); } public function can_edit() { $auth = $this->auth(); return is_wp_error( $auth ) ? $auth : ( WP_Assessment_Permissions::can_edit( 'answer' ) ? true : new WP_Error( 'forbidden', 'You do not have permission to edit answers.', array( 'status' => 403 ) ) ); } public function can_delete() { $auth = $this->auth(); return is_wp_error( $auth ) ? $auth : ( WP_Assessment_Permissions::can_delete( 'answer' ) ? true : new WP_Error( 'forbidden', 'You do not have permission to delete answers.', array( 'status' => 403 ) ) ); }
    private function question( $id ) { global $wpdb; return $wpdb->get_row( $wpdb->prepare( "SELECT q.*, a.status AS assessment_status FROM {$wpdb->prefix}assessment_questions q INNER JOIN {$wpdb->prefix}assessment a ON a.id = q.assessment_id WHERE q.id = %d", $id ) ); }
    public function get_items( $request ) { global $wpdb; $question = $this->question( absint( $request['id'] ) ); if ( ! $question || ( ( $question->status !== 'publish' || $question->assessment_status !== 'publish' ) && ! $this->manager() ) ) { return new WP_Error( 'not_found', 'Question not found.', array( 'status' => 404 ) ); } $table = $wpdb->prefix . 'assessment_answers'; $users = $wpdb->users; $items = $wpdb->get_results( $wpdb->prepare( "SELECT r.*, u.display_name AS author_name FROM $table r LEFT JOIN $users u ON r.user_id = u.ID WHERE r.question_id = %d ORDER BY r.created_at ASC, r.id ASC", $question->id ) ); foreach ( $items as $item ) { $item->author_name = $item->author_name ? $item->author_name : 'Hệ thống'; $item->author_avatar = $item->user_id ? get_avatar_url( $item->user_id, array( 'size' => 80 ) ) : ''; } return rest_ensure_response( $items ); }
    public function create_item( $request ) {
        global $wpdb;
        $question_id = absint( $request->get_param( 'question_id' ) );
        $content = wp_kses_post( $request->get_param( 'content' ) );
        if ( ! $this->question( $question_id ) || $content === '' ) {
            return new WP_Error( 'invalid_data', 'A valid question and answer content are required.', array( 'status' => 422 ) );
        }
        $table = $wpdb->prefix . 'assessment_answers';
        if ( false === $wpdb->insert( $table, array( 'question_id' => $question_id, 'user_id' => get_current_user_id(), 'content' => $content, 'score' => intval( $request->get_param( 'score' ) ), 'sort_order' => absint( $request->get_param( 'sort_order' ) ), 'created_at' => current_time( 'mysql', true ) ), array( '%d', '%d', '%s', '%d', '%d', '%s' ) ) ) {
            return new WP_Error( 'db_error', 'Could not create answer.', array( 'status' => 500 ) );
        }
        return new WP_REST_Response( $wpdb->get_row( $wpdb->prepare( "SELECT * FROM $table WHERE id = %d", $wpdb->insert_id ) ), 201 );
    }
    public function update_item( $request ) { global $wpdb; $table = $wpdb->prefix . 'assessment_answers'; $id = absint( $request['id'] ); $item = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM $table WHERE id = %d", $id ) ); if ( ! $item ) { return new WP_Error( 'not_found', 'Answer not found.', array( 'status' => 404 ) ); } $content = $request->has_param( 'content' ) ? wp_kses_post( $request->get_param( 'content' ) ) : $item->content; if ( $content === '' ) { return new WP_Error( 'invalid_data', 'Answer content is required.', array( 'status' => 422 ) ); } $wpdb->update( $table, array( 'content' => $content, 'score' => $request->has_param( 'score' ) ? intval( $request->get_param( 'score' ) ) : $item->score, 'sort_order' => $request->has_param( 'sort_order' ) ? absint( $request->get_param( 'sort_order' ) ) : $item->sort_order ), array( 'id' => $id ), array( '%s', '%d', '%d' ), array( '%d' ) ); return rest_ensure_response( $wpdb->get_row( $wpdb->prepare( "SELECT * FROM $table WHERE id = %d", $id ) ) ); }
    public function delete_item( $request ) { global $wpdb; $table = $wpdb->prefix . 'assessment_answers'; $id = absint( $request['id'] ); if ( ! $wpdb->get_var( $wpdb->prepare( "SELECT id FROM $table WHERE id = %d", $id ) ) ) { return new WP_Error( 'not_found', 'Answer not found.', array( 'status' => 404 ) ); } $wpdb->delete( $table, array( 'id' => $id ), array( '%d' ) ); return rest_ensure_response( array( 'deleted' => true, 'id' => $id ) ); }
}
