<?php
class WP_Assessment_Question_Controller extends WP_REST_Controller {
    public function __construct() { $this->namespace = 'assessment/v1'; $this->rest_base = 'questions'; }
    public function register_routes() {
        register_rest_route( $this->namespace, '/assessments/(?P<id>\\d+)/questions', array( 'methods' => WP_REST_Server::READABLE, 'callback' => array( $this, 'get_items' ), 'permission_callback' => '__return_true' ) );
        register_rest_route( $this->namespace, '/questions', array( 'methods' => WP_REST_Server::CREATABLE, 'callback' => array( $this, 'create_item' ), 'permission_callback' => array( $this, 'can_create' ) ) );
        register_rest_route( $this->namespace, '/questions/(?P<id>\\d+)', array( array( 'methods' => WP_REST_Server::EDITABLE, 'callback' => array( $this, 'update_item' ), 'permission_callback' => array( $this, 'can_edit' ) ), array( 'methods' => WP_REST_Server::DELETABLE, 'callback' => array( $this, 'delete_item' ), 'permission_callback' => array( $this, 'can_delete' ) ) ) );
    }
    private function auth() { return ( new WP_Assessment_JWT_Auth() )->authenticate_request(); }
    private function manager() { $auth = $this->auth(); return ! is_wp_error( $auth ) && WP_Assessment_Permissions::can_view( 'question' ); }
    public function can_create() { $auth = $this->auth(); return is_wp_error( $auth ) ? $auth : ( WP_Assessment_Permissions::can_create_question() ? true : new WP_Error( 'forbidden', 'You do not have permission to create questions.', array( 'status' => 403 ) ) ); }
    public function can_edit() { $auth = $this->auth(); return is_wp_error( $auth ) ? $auth : ( WP_Assessment_Permissions::can_edit( 'question' ) ? true : new WP_Error( 'forbidden', 'You do not have permission to edit questions.', array( 'status' => 403 ) ) ); }
    public function can_delete() { $auth = $this->auth(); return is_wp_error( $auth ) ? $auth : ( WP_Assessment_Permissions::can_delete( 'question' ) ? true : new WP_Error( 'forbidden', 'You do not have permission to delete questions.', array( 'status' => 403 ) ) ); }
    private function valid_status( $status ) { return in_array( $status, array( 'draft', 'publish' ), true ); }
    private function assessment( $id ) { global $wpdb; return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}assessment WHERE id = %d", $id ) ); }
    public function get_items( $request ) { global $wpdb; $assessment = $this->assessment( absint( $request['id'] ) ); if ( ! $assessment || ( $assessment->status !== 'publish' && ! $this->manager() ) ) { return new WP_Error( 'not_found', 'Assessment not found.', array( 'status' => 404 ) ); } $table = $wpdb->prefix . 'assessment_questions'; $users = $wpdb->users; $per_page = min( 100, max( 1, absint( $request->get_param( 'per_page' ) ?: 10 ) ) ); $page = max( 1, absint( $request->get_param( 'page' ) ?: 1 ) ); $where = $this->manager() ? 'q.assessment_id = %d' : "q.assessment_id = %d AND q.status = 'publish'"; $where = $wpdb->prepare( $where, $assessment->id ); $search = sanitize_text_field( (string) $request->get_param( 'search' ) ); if ( $search !== '' ) { $where .= $wpdb->prepare( ' AND q.content LIKE %s', '%' . $wpdb->esc_like( $search ) . '%' ); } $total = (int) $wpdb->get_var( "SELECT COUNT(*) FROM $table q WHERE $where" ); $items = $wpdb->get_results( $wpdb->prepare( "SELECT q.*, u.display_name AS author_name FROM $table q LEFT JOIN $users u ON q.user_id = u.ID WHERE $where ORDER BY q.sort_order ASC, q.id ASC LIMIT %d OFFSET %d", $per_page, ( $page - 1 ) * $per_page ) ); foreach ( $items as $item ) { $item->author_name = $item->author_name ? $item->author_name : 'Hệ thống'; $item->author_avatar = $item->user_id ? get_avatar_url( $item->user_id, array( 'size' => 80 ) ) : ''; } $response = rest_ensure_response( $items ); $response->header( 'X-WP-Total', $total ); $response->header( 'X-WP-TotalPages', (int) ceil( $total / $per_page ) ); return $response; }
    public function create_item( $request ) { global $wpdb; $assessment_id = absint( $request->get_param( 'assessment_id' ) ); $content = wp_kses_post( $request->get_param( 'content' ) ); $status = sanitize_key( $request->get_param( 'status' ) ?: 'publish' ); $sort_order = absint( $request->get_param( 'sort_order' ) ); if ( ! $this->assessment( $assessment_id ) || $content === '' || ! $this->valid_status( $status ) ) { return new WP_Error( 'invalid_data', 'A valid assessment, content and status are required.', array( 'status' => 422 ) ); } $table = $wpdb->prefix . 'assessment_questions'; if ( false === $wpdb->insert( $table, array( 'assessment_id' => $assessment_id, 'user_id' => get_current_user_id(), 'content' => $content, 'sort_order' => $sort_order, 'status' => $status, 'created_at' => current_time( 'mysql', true ) ), array( '%d', '%d', '%s', '%d', '%s', '%s' ) ) ) { WP_Assessment_Logger::database_error( 'create_question' ); return new WP_Error( 'db_error', 'Could not create question.', array( 'status' => 500 ) ); } return new WP_REST_Response( $wpdb->get_row( $wpdb->prepare( "SELECT * FROM $table WHERE id = %d", $wpdb->insert_id ) ), 201 ); }
    public function update_item( $request ) { global $wpdb; $table = $wpdb->prefix . 'assessment_questions'; $id = absint( $request['id'] ); $item = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM $table WHERE id = %d", $id ) ); if ( ! $item ) { return new WP_Error( 'not_found', 'Question not found.', array( 'status' => 404 ) ); } $content = $request->has_param( 'content' ) ? wp_kses_post( $request->get_param( 'content' ) ) : $item->content; $status = $request->has_param( 'status' ) ? sanitize_key( $request->get_param( 'status' ) ) : $item->status; if ( $content === '' || ! $this->valid_status( $status ) ) { return new WP_Error( 'invalid_data', 'Content and status are invalid.', array( 'status' => 422 ) ); } $wpdb->update( $table, array( 'content' => $content, 'sort_order' => $request->has_param( 'sort_order' ) ? absint( $request->get_param( 'sort_order' ) ) : $item->sort_order, 'status' => $status ), array( 'id' => $id ), array( '%s', '%d', '%s' ), array( '%d' ) ); return rest_ensure_response( $wpdb->get_row( $wpdb->prepare( "SELECT * FROM $table WHERE id = %d", $id ) ) ); }
    public function delete_item( $request ) { global $wpdb; $id = absint( $request['id'] ); $questions = $wpdb->prefix . 'assessment_questions'; $answers = $wpdb->prefix . 'assessment_answers'; if ( ! $wpdb->get_var( $wpdb->prepare( "SELECT id FROM $questions WHERE id = %d", $id ) ) ) { return new WP_Error( 'not_found', 'Question not found.', array( 'status' => 404 ) ); } $wpdb->delete( $answers, array( 'question_id' => $id ), array( '%d' ) ); $wpdb->delete( $questions, array( 'id' => $id ), array( '%d' ) ); return rest_ensure_response( array( 'deleted' => true, 'id' => $id ) ); }
}
