<?php

class WP_Assessment_Admin {
    public static function register_menu() {
        // Use the long-standing module capability for menu visibility; page actions remain
        // protected individually by the View/Create/Edit/Delete checks below.
        add_menu_page( 'Mini Assessment', 'Mini Assessment', 'manage_assessments', 'wp-assessment', array( __CLASS__, 'render_assessments' ), 'dashicons-clipboard', 30 );
        add_submenu_page( 'wp-assessment', 'Bài đánh giá', 'Bài đánh giá', 'manage_assessments', 'wp-assessment', array( __CLASS__, 'render_assessments' ) );
        add_submenu_page( 'wp-assessment', 'Câu hỏi', 'Câu hỏi', 'manage_assessments', 'wp-assessment-questions', array( __CLASS__, 'render_questions' ) );
        add_submenu_page( 'wp-assessment', 'Phương án trả lời', 'Phương án trả lời', 'manage_assessments', 'wp-assessment-answers', array( __CLASS__, 'render_answers' ) );
        add_submenu_page( 'wp-assessment', 'Phân quyền role', 'Phân quyền role', 'manage_assessments', 'wp-assessment-permissions', array( __CLASS__, 'render_permissions' ) );
    }
    public static function notices() { settings_errors( 'wp_assessment_admin' ); }
    private static function guard( $entity = 'assessment', $action = 'view' ) { if ( ! WP_Assessment_Permissions::can( $entity, $action ) ) { wp_die( esc_html__( 'You do not have permission to access this page.', 'wp-assessment' ) ); } }
    public static function handle_actions() {
        if ( ! is_admin() || empty( $_POST['wp_assessment_action'] ) ) { return; }
        $action = sanitize_key( wp_unslash( $_POST['wp_assessment_action'] ) );
        if ( ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['_wpnonce'] ?? '' ) ), 'wp_assessment_admin_action' ) ) { wp_die( 'Invalid request.' ); }
        $kind = sanitize_key( wp_unslash( $_POST['kind'] ?? '' ) );
        if ( ! in_array( $kind, array( 'assessment', 'question', 'answer' ), true ) ) { return; }
        self::guard( $kind, $action === 'delete' ? 'delete' : ( $action === 'save' ? ( absint( $_POST['id'] ?? 0 ) ? 'edit' : 'create' ) : 'view' ) );
        global $wpdb; $tables = array( 'assessment' => $wpdb->prefix . 'assessment', 'question' => $wpdb->prefix . 'assessment_questions', 'answer' => $wpdb->prefix . 'assessment_answers' ); $table = $tables[ $kind ];
        if ( $action === 'delete' ) { $id = absint( $_POST['id'] ?? 0 ); if ( $kind === 'assessment' ) { $question_ids = $wpdb->get_col( $wpdb->prepare( "SELECT id FROM {$tables['question']} WHERE assessment_id=%d", $id ) ); foreach ( $question_ids as $question_id ) { $wpdb->delete( $tables['answer'], array( 'question_id' => $question_id ), array( '%d' ) ); } $wpdb->delete( $tables['question'], array( 'assessment_id' => $id ), array( '%d' ) ); } elseif ( $kind === 'question' ) { $wpdb->delete( $tables['answer'], array( 'question_id' => $id ), array( '%d' ) ); } $wpdb->delete( $table, array( 'id' => $id ), array( '%d' ) ); self::redirect( $kind, 'deleted' ); }
        $id = absint( $_POST['id'] ?? 0 ); $data = self::form_data( $kind );
        if ( $kind === 'assessment' && $data['title'] === '' ) { self::redirect( $kind, 'invalid' ); }
        if ( in_array( $kind, array( 'question', 'answer' ), true ) && $data['content'] === '' ) { self::redirect( $kind, 'invalid' ); }
        if ( $id ) { $wpdb->update( $table, $data, array( 'id' => $id ) ); self::redirect( $kind, 'updated' ); }
        $wpdb->insert( $table, $data ); self::redirect( $kind, 'created' );
    }
    private static function form_data( $kind ) {
        if ( $kind === 'assessment' ) { return array( 'title' => sanitize_text_field( wp_unslash( $_POST['title'] ?? '' ) ), 'description' => wp_kses_post( wp_unslash( $_POST['description'] ?? '' ) ), 'status' => in_array( $_POST['status'] ?? '', array( 'draft', 'publish' ), true ) ? $_POST['status'] : 'draft' ); }
        if ( $kind === 'question' ) { return array( 'assessment_id' => absint( $_POST['assessment_id'] ?? 0 ), 'content' => wp_kses_post( wp_unslash( $_POST['content'] ?? '' ) ), 'sort_order' => absint( $_POST['sort_order'] ?? 0 ), 'status' => in_array( $_POST['status'] ?? '', array( 'draft', 'publish' ), true ) ? $_POST['status'] : 'draft' ); }
        return array( 'question_id' => absint( $_POST['question_id'] ?? 0 ), 'content' => wp_kses_post( wp_unslash( $_POST['content'] ?? '' ) ), 'score' => intval( $_POST['score'] ?? 0 ), 'sort_order' => absint( $_POST['sort_order'] ?? 0 ) );
    }
    private static function redirect( $kind, $notice ) { $pages = array( 'assessment' => 'wp-assessment', 'question' => 'wp-assessment-questions', 'answer' => 'wp-assessment-answers' ); wp_safe_redirect( admin_url( 'admin.php?page=' . $pages[ $kind ] . '&notice=' . $notice ) ); exit; }
    private static function top( $title, $kind ) { self::guard( $kind, 'view' ); echo '<div class="wrap"><h1 class="wp-heading-inline">' . esc_html( $title ) . '</h1>'; if ( WP_Assessment_Permissions::can_create( $kind ) ) { echo ' <a href="#wp-assessment-form" class="page-title-action">Add new</a>'; } if ( isset( $_GET['notice'] ) ) { echo '<div class="notice notice-success is-dismissible"><p>Item ' . esc_html( sanitize_key( $_GET['notice'] ) ) . '.</p></div>'; } }
    private static function bottom() { echo '</div>'; }
    private static function edit_item( $kind ) { global $wpdb; $id = absint( $_GET['edit'] ?? 0 ); if ( ! $id ) { return null; } $tables = array( 'assessment' => 'assessment', 'question' => 'assessment_questions', 'answer' => 'assessment_answers' ); return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}{$tables[$kind]} WHERE id=%d", $id ), ARRAY_A ); }
    private static function select_options( $table, $label, $selected ) { global $wpdb; $rows = $wpdb->get_results( "SELECT id, $label AS label FROM {$wpdb->prefix}$table ORDER BY id DESC" ); foreach ( $rows as $row ) { printf( '<option value="%d" %s>#%d - %s</option>', $row->id, selected( $selected, $row->id, false ), $row->id, esc_html( wp_strip_all_tags( $row->label ) ) ); } }
    private static function form( $kind, $item = null ) { if ( ! WP_Assessment_Permissions::can_create( $kind ) && ! ( $item && WP_Assessment_Permissions::can_edit( $kind ) ) ) { return; } $item = $item ?: array(); echo '<hr><h2 id="wp-assessment-form">' . ( $item ? 'Edit' : 'Add new' ) . '</h2><form method="post">'; wp_nonce_field( 'wp_assessment_admin_action' ); echo '<input type="hidden" name="wp_assessment_action" value="save"><input type="hidden" name="kind" value="' . esc_attr( $kind ) . '"><input type="hidden" name="id" value="' . absint( $item['id'] ?? 0 ) . '"><table class="form-table"><tbody>';
        if ( $kind === 'assessment' ) { self::input( 'Title', 'title', $item['title'] ?? '' ); echo '<tr><th>Description</th><td><textarea name="description" rows="4" class="large-text">' . esc_textarea( $item['description'] ?? '' ) . '</textarea></td></tr>'; self::status( $item['status'] ?? 'draft' ); }
        if ( $kind === 'question' ) { echo '<tr><th>Assessment</th><td><select name="assessment_id">'; self::select_options( 'assessment', 'title', $item['assessment_id'] ?? 0 ); echo '</select></td></tr>'; self::textarea( 'Content', 'content', $item['content'] ?? '' ); self::input( 'Sort order', 'sort_order', $item['sort_order'] ?? 0, 'number' ); self::status( $item['status'] ?? 'draft' ); }
        if ( $kind === 'answer' ) { echo '<tr><th>Question</th><td><select name="question_id">'; self::select_options( 'assessment_questions', 'content', $item['question_id'] ?? 0 ); echo '</select></td></tr>'; self::textarea( 'Content', 'content', $item['content'] ?? '' ); self::input( 'Score', 'score', $item['score'] ?? 0, 'number' ); self::input( 'Sort order', 'sort_order', $item['sort_order'] ?? 0, 'number' ); }
        echo '</tbody></table><p><button class="button button-primary">Save</button></p></form>';
    }
    private static function input( $label, $name, $value, $type = 'text' ) { echo '<tr><th>' . esc_html( $label ) . '</th><td><input required class="regular-text" type="' . esc_attr( $type ) . '" name="' . esc_attr( $name ) . '" value="' . esc_attr( $value ) . '"></td></tr>'; }
    private static function textarea( $label, $name, $value ) { echo '<tr><th>' . esc_html( $label ) . '</th><td><textarea required name="' . esc_attr( $name ) . '" rows="4" class="large-text">' . esc_textarea( $value ) . '</textarea></td></tr>'; }
    private static function status( $value ) { echo '<tr><th>Status</th><td><select name="status"><option value="draft" ' . selected( $value, 'draft', false ) . '>Draft</option><option value="publish" ' . selected( $value, 'publish', false ) . '>Publish</option></select></td></tr>'; }
    private static function actions( $kind, $id ) { $page = array( 'assessment' => 'wp-assessment', 'question' => 'wp-assessment-questions', 'answer' => 'wp-assessment-answers' )[ $kind ]; echo WP_Assessment_Permissions::can_edit( $kind ) ? '<a href="' . esc_url( admin_url( 'admin.php?page=' . $page . '&edit=' . $id ) ) . '">Edit</a> ' : ''; if ( WP_Assessment_Permissions::can_delete( $kind ) ) { echo '<form method="post" style="display:inline">'; wp_nonce_field( 'wp_assessment_admin_action' ); echo '<input type="hidden" name="wp_assessment_action" value="delete"><input type="hidden" name="kind" value="' . esc_attr( $kind ) . '"><input type="hidden" name="id" value="' . absint( $id ) . '"><button class="button-link-delete" onclick="return confirm(\'Delete this item and child data?\')">Delete</button></form>'; } }
    public static function render_assessments() { global $wpdb; self::top( 'Assessments', 'assessment' ); $rows = $wpdb->get_results( "SELECT * FROM {$wpdb->prefix}assessment ORDER BY id DESC" ); echo '<table class="widefat striped"><thead><tr><th>ID</th><th>Title</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>'; foreach ( $rows as $row ) { echo '<tr><td>' . $row->id . '</td><td>' . esc_html( $row->title ) . '</td><td>' . esc_html( $row->status ) . '</td><td>' . esc_html( $row->updated_at ) . '</td><td>'; self::actions( 'assessment', $row->id ); echo '</td></tr>'; } echo '</tbody></table>'; self::form( 'assessment', self::edit_item( 'assessment' ) ); self::bottom(); }
    public static function render_questions() { global $wpdb; self::top( 'Questions', 'question' ); $rows = $wpdb->get_results( "SELECT q.*, a.title FROM {$wpdb->prefix}assessment_questions q LEFT JOIN {$wpdb->prefix}assessment a ON q.assessment_id=a.id ORDER BY q.assessment_id, q.sort_order, q.id" ); echo '<table class="widefat striped"><thead><tr><th>ID</th><th>Assessment</th><th>Question</th><th>Status</th><th>Order</th><th>Actions</th></tr></thead><tbody>'; foreach ( $rows as $row ) { echo '<tr><td>' . $row->id . '</td><td>' . esc_html( $row->title ) . '</td><td>' . esc_html( wp_trim_words( wp_strip_all_tags( $row->content ), 12 ) ) . '</td><td>' . esc_html( $row->status ) . '</td><td>' . $row->sort_order . '</td><td>'; self::actions( 'question', $row->id ); echo '</td></tr>'; } echo '</tbody></table>'; self::form( 'question', self::edit_item( 'question' ) ); self::bottom(); }
    public static function render_answers() { global $wpdb; self::top( 'Answers', 'answer' ); $rows = $wpdb->get_results( "SELECT r.*, q.content question FROM {$wpdb->prefix}assessment_answers r LEFT JOIN {$wpdb->prefix}assessment_questions q ON r.question_id=q.id ORDER BY r.question_id, r.sort_order, r.id" ); echo '<table class="widefat striped"><thead><tr><th>ID</th><th>Question</th><th>Answer</th><th>Score</th><th>Order</th><th>Actions</th></tr></thead><tbody>'; foreach ( $rows as $row ) { echo '<tr><td>' . $row->id . '</td><td>' . esc_html( wp_trim_words( wp_strip_all_tags( $row->question ), 8 ) ) . '</td><td>' . esc_html( wp_trim_words( wp_strip_all_tags( $row->content ), 12 ) ) . '</td><td>' . $row->score . '</td><td>' . $row->sort_order . '</td><td>'; self::actions( 'answer', $row->id ); echo '</td></tr>'; } echo '</tbody></table>'; self::form( 'answer', self::edit_item( 'answer' ) ); self::bottom(); }
    public static function render_permissions() { if ( ! WP_Assessment_Permissions::can_manage_permissions() ) { wp_die( 'You do not have permission to manage role permissions.' ); } if ( isset( $_POST['wp_assessment_permissions_nonce'] ) && wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['wp_assessment_permissions_nonce'] ) ), 'wp_assessment_permissions' ) ) { $submitted = (array) wp_unslash( $_POST['permissions'] ?? array() ); $permissions = array(); foreach ( wp_roles()->roles as $role_key => $role_data ) { if ( in_array( $role_key, array( 'administrator', 'assessment_manager' ), true ) ) { continue; } foreach ( WP_Assessment_Permissions::all_permission_keys() as $permission ) { $permissions[ $role_key ][ $permission ] = ! empty( $submitted[ $role_key ][ $permission ] ); } } update_option( WP_ASSESSMENT_PERMISSION_OPTION, $permissions, false ); WP_Assessment_Permissions::sync_role_capabilities( $permissions ); echo '<div class="notice notice-success"><p>Permissions saved.</p></div>'; } $permissions = WP_Assessment_Permissions::permissions(); echo '<div class="wrap"><h1>Mini Assessment - Role permissions</h1><p>Each row is one permission. Each column is an existing WordPress role. Assessment Manager and Administrator always have full access.</p><form method="post">'; wp_nonce_field( 'wp_assessment_permissions', 'wp_assessment_permissions_nonce' ); echo '<table class="widefat striped"><thead><tr><th>Permission</th>'; foreach ( wp_roles()->roles as $role_key => $role_data ) { echo '<th>' . esc_html( translate_user_role( $role_data['name'] ) ) . '</th>'; } echo '</tr></thead><tbody>'; foreach ( WP_Assessment_Permissions::entities() as $entity => $entity_label ) { foreach ( WP_Assessment_Permissions::actions() as $action ) { $permission = WP_Assessment_Permissions::permission_key( $entity, $action ); echo '<tr><td><strong>' . esc_html( $entity_label ) . '</strong> - ' . esc_html( ucfirst( $action ) ) . '</td>'; foreach ( wp_roles()->roles as $role_key => $role_data ) { if ( in_array( $role_key, array( 'administrator', 'assessment_manager' ), true ) ) { echo '<td><strong>Full</strong></td>'; } else { printf( '<td><input type="checkbox" name="permissions[%s][%s]" value="1" %s></td>', esc_attr( $role_key ), esc_attr( $permission ), checked( ! empty( $permissions[ $role_key ][ $permission ] ), true, false ) ); } } echo '</tr>'; } } echo '</tbody></table><p class="submit"><button class="button button-primary">Save permissions</button></p></form></div>'; }
}
add_action( 'admin_init', array( 'WP_Assessment_Admin', 'handle_actions' ) );
