<?php

class WP_Assessment_Admin {
    public static function register_menu() {
        // Use the long-standing module capability for menu visibility; page actions remain
        // protected individually by the View/Create/Edit/Delete checks below.
        add_menu_page( 'Mini Assessment', 'Mini Assessment', 'manage_assessments', 'wp-assessment', array( __CLASS__, 'render_assessments' ), 'dashicons-clipboard', 30 );
        add_submenu_page( 'wp-assessment', 'Bài đánh giá', 'Bài đánh giá', 'manage_assessments', 'wp-assessment', array( __CLASS__, 'render_assessments' ) );
        add_submenu_page( 'wp-assessment', 'Câu hỏi', 'Câu hỏi', 'manage_assessments', 'wp-assessment-questions', array( __CLASS__, 'render_questions' ) );
        add_submenu_page( 'wp-assessment', 'Phương án trả lời', 'Phương án trả lời', 'manage_assessments', 'wp-assessment-answers', array( __CLASS__, 'render_answers' ) );
        add_submenu_page( 'wp-assessment', 'Phân quyền role', 'Phân quyền role', 'manage_assessments', 'wp-assessment-permissions', array( __CLASS__, 'render_permissions' ) );
    }
    public static function notices() { settings_errors( 'wp_assessment_admin' ); }
    public static function enqueue_assets( $hook ) {
        if ( 'toplevel_page_wp-assessment' !== $hook || ! WP_Assessment_Permissions::can_edit( 'assessment' ) ) { return; }
        wp_enqueue_script( 'jquery-ui-sortable' );
        wp_add_inline_script( 'jquery-ui-sortable', "document.addEventListener('DOMContentLoaded', function () { document.querySelectorAll('[data-wp-assessment-sortable]').forEach(function (body) { const save = document.querySelector(body.dataset.saveButton); let dragged; if (!save) return; body.querySelectorAll('tr[draggable=\"true\"]').forEach(function (row) { row.addEventListener('dragstart', function (event) { dragged = row; row.classList.add('wp-assessment-dragging'); event.dataTransfer.effectAllowed = 'move'; }); row.addEventListener('dragend', function () { row.classList.remove('wp-assessment-dragging'); dragged = null; }); row.addEventListener('dragover', function (event) { event.preventDefault(); if (!dragged || dragged === row) return; const bounds = row.getBoundingClientRect(); body.insertBefore(dragged, event.clientY < bounds.top + bounds.height / 2 ? row : row.nextSibling); save.disabled = false; }); }); }); document.querySelectorAll('.wp-assessment-open-question').forEach(function (button) { button.addEventListener('click', function () { const modal = document.getElementById(button.dataset.modal); if (modal) modal.hidden = false; }); }); document.querySelectorAll('.wp-assessment-modal-close').forEach(function (button) { button.addEventListener('click', function () { button.closest('.wp-assessment-modal').hidden = true; }); }); document.addEventListener('keydown', function (event) { if (event.key === 'Escape') { const modal = document.querySelector('.wp-assessment-modal:not([hidden])'); if (modal) modal.hidden = true; } }); });" );
        wp_add_inline_script( 'jquery-ui-sortable', "document.addEventListener('DOMContentLoaded', function () { document.querySelectorAll('.wp-assessment-add-answer').forEach(function (button) { button.addEventListener('click', function () { const target = document.getElementById(button.dataset.target); const template = document.getElementById(button.dataset.template); if (target && template) target.appendChild(template.content.cloneNode(true)); }); }); });" );
        wp_add_inline_style( 'common', '[data-wp-assessment-sortable] tr[draggable="true"] { cursor: grab; } [data-wp-assessment-sortable] tr.wp-assessment-dragging { opacity: .45; } .wp-assessment-drag-handle { color: #646970; cursor: grab; } .wp-assessment-modal { position: fixed; z-index: 100000; inset: 0; overflow: auto; padding: 48px 20px; background: rgba(0,0,0,.45); } .wp-assessment-modal__content { width: min(100%, 960px); margin: 0 auto; padding: 24px; background: #fff; box-shadow: 0 12px 42px rgba(0,0,0,.3); } .wp-assessment-modal__header { display: flex; align-items: center; justify-content: space-between; gap: 16px; } .wp-assessment-modal textarea { width: 100%; min-height: 76px; }' );
    }
    private static function guard( $entity = 'assessment', $action = 'view' ) { if ( ! WP_Assessment_Permissions::can( $entity, $action ) ) { wp_die( esc_html__( 'You do not have permission to access this page.', 'wp-assessment' ) ); } }
    public static function handle_actions() {
        if ( ! is_admin() || empty( $_POST['wp_assessment_action'] ) ) { return; }
        $action = sanitize_key( wp_unslash( $_POST['wp_assessment_action'] ) );
        if ( ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['_wpnonce'] ?? '' ) ), 'wp_assessment_admin_action' ) ) { wp_die( 'Invalid request.' ); }
        $kind = sanitize_key( wp_unslash( $_POST['kind'] ?? '' ) );
        if ( ! in_array( $kind, array( 'assessment', 'question', 'answer' ), true ) ) { return; }
        if ( $action === 'reorder' ) {
            self::guard( $kind, 'edit' );
            if ( $kind !== 'assessment' ) { self::redirect( $kind, 'invalid' ); }
            $submitted = isset( $_POST['order'] ) ? array_map( 'absint', (array) wp_unslash( $_POST['order'] ) ) : array();
            $submitted = array_values( array_filter( $submitted ) );
            global $wpdb;
            $table = $wpdb->prefix . 'assessment';
            $existing = array_map( 'absint', $wpdb->get_col( "SELECT id FROM $table" ) );
            $expected = $submitted;
            sort( $expected ); sort( $existing );
            if ( count( $submitted ) !== count( array_unique( $submitted ) ) || $expected !== $existing ) { self::redirect( $kind, 'invalid' ); }
            foreach ( $submitted as $position => $id ) { $wpdb->update( $table, array( 'sort_order' => $position + 1 ), array( 'id' => $id ), array( '%d' ), array( '%d' ) ); }
            self::redirect( $kind, 'order-saved' );
        }
        if ( $action === 'reorder_questions' ) {
            self::guard( 'question', 'edit' );
            $assessment_id = absint( $_POST['assessment_id'] ?? 0 );
            $submitted = isset( $_POST['order'] ) ? array_values( array_filter( array_map( 'absint', (array) wp_unslash( $_POST['order'] ) ) ) ) : array();
            global $wpdb;
            $table = $wpdb->prefix . 'assessment_questions';
            $existing = array_map( 'absint', $wpdb->get_col( $wpdb->prepare( "SELECT id FROM $table WHERE assessment_id = %d", $assessment_id ) ) );
            $expected = $submitted; sort( $expected ); sort( $existing );
            if ( ! $assessment_id || count( $submitted ) !== count( array_unique( $submitted ) ) || $expected !== $existing ) { self::redirect_assessment_detail( $assessment_id, 'invalid' ); }
            foreach ( $submitted as $position => $id ) { $wpdb->update( $table, array( 'sort_order' => $position + 1 ), array( 'id' => $id ), array( '%d' ), array( '%d' ) ); }
            self::redirect_assessment_detail( $assessment_id, 'order-saved' );
        }
        if ( $action === 'save_question_detail' ) {
            self::guard( 'question', 'edit' );
            $assessment_id = absint( $_POST['assessment_id'] ?? 0 ); $question_id = absint( $_POST['id'] ?? 0 );
            global $wpdb;
            $questions = $wpdb->prefix . 'assessment_questions'; $answers = $wpdb->prefix . 'assessment_answers';
            $question = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM $questions WHERE id = %d AND assessment_id = %d", $question_id, $assessment_id ) );
            $content = wp_kses_post( wp_unslash( $_POST['content'] ?? '' ) ); $status = sanitize_key( wp_unslash( $_POST['status'] ?? '' ) );
            if ( ! $question || $content === '' || ! in_array( $status, array( 'draft', 'publish' ), true ) ) { self::redirect_assessment_detail( $assessment_id, 'invalid' ); }
            $wpdb->update( $questions, array( 'content' => $content, 'status' => $status ), array( 'id' => $question_id ), array( '%s', '%s' ), array( '%d' ) );
            if ( WP_Assessment_Permissions::can_edit( 'answer' ) ) {
                $order = isset( $_POST['answer_order'] ) ? array_values( array_filter( array_map( 'absint', (array) wp_unslash( $_POST['answer_order'] ) ) ) ) : array();
                $existing = array_map( 'absint', $wpdb->get_col( $wpdb->prepare( "SELECT id FROM $answers WHERE question_id = %d", $question_id ) ) );
                $delete_ids = isset( $_POST['delete_answers'] ) ? array_values( array_filter( array_map( 'absint', (array) wp_unslash( $_POST['delete_answers'] ) ) ) ) : array();
                $remaining = array_values( array_diff( $existing, $delete_ids ) ); $expected = $order; sort( $expected ); sort( $remaining );
                $submitted_answers = (array) wp_unslash( $_POST['answers'] ?? array() );
                if ( count( $order ) !== count( array_unique( $order ) ) || count( $delete_ids ) !== count( array_unique( $delete_ids ) ) || array_diff( $delete_ids, $existing ) || $expected !== $remaining ) { self::redirect_assessment_detail( $assessment_id, 'invalid' ); }
                foreach ( $delete_ids as $answer_id ) { $wpdb->delete( $answers, array( 'id' => $answer_id, 'question_id' => $question_id ), array( '%d', '%d' ) ); }
                foreach ( $order as $position => $answer_id ) { $answer = (array) ( $submitted_answers[ $answer_id ] ?? array() ); $answer_content = wp_kses_post( $answer['content'] ?? '' ); if ( $answer_content === '' ) { self::redirect_assessment_detail( $assessment_id, 'invalid' ); } $wpdb->update( $answers, array( 'content' => $answer_content, 'sort_order' => $position + 1 ), array( 'id' => $answer_id, 'question_id' => $question_id ), array( '%s', '%d' ), array( '%d', '%d' ) ); }
            }
            if ( WP_Assessment_Permissions::can_create( 'answer' ) ) {
                $new_answers = (array) wp_unslash( $_POST['new_answers'] ?? array() );
                $next_sort_order = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COALESCE(MAX(sort_order), 0) + 1 FROM $answers WHERE question_id = %d", $question_id ) );
                foreach ( $new_answers as $new_answer ) { $new_answer = (array) $new_answer; $answer_content = wp_kses_post( $new_answer['content'] ?? '' ); if ( $answer_content === '' ) { continue; } $wpdb->insert( $answers, array( 'question_id' => $question_id, 'user_id' => get_current_user_id(), 'content' => $answer_content, 'score' => intval( $new_answer['score'] ?? 0 ), 'sort_order' => $next_sort_order++ ), array( '%d', '%d', '%s', '%d', '%d' ) ); }
            }
            self::redirect_assessment_detail( $assessment_id, 'updated' );
        }
        self::guard( $kind, $action === 'delete' ? 'delete' : ( $action === 'save' ? ( absint( $_POST['id'] ?? 0 ) ? 'edit' : 'create' ) : 'view' ) );
        global $wpdb; $tables = array( 'assessment' => $wpdb->prefix . 'assessment', 'question' => $wpdb->prefix . 'assessment_questions', 'answer' => $wpdb->prefix . 'assessment_answers' ); $table = $tables[ $kind ];
        if ( $action === 'delete' ) { $id = absint( $_POST['id'] ?? 0 ); if ( $kind === 'assessment' ) { $question_ids = $wpdb->get_col( $wpdb->prepare( "SELECT id FROM {$tables['question']} WHERE assessment_id=%d", $id ) ); foreach ( $question_ids as $question_id ) { $wpdb->delete( $tables['answer'], array( 'question_id' => $question_id ), array( '%d' ) ); } $wpdb->delete( $tables['question'], array( 'assessment_id' => $id ), array( '%d' ) ); } elseif ( $kind === 'question' ) { $wpdb->delete( $tables['answer'], array( 'question_id' => $id ), array( '%d' ) ); } $wpdb->delete( $table, array( 'id' => $id ), array( '%d' ) ); self::redirect( $kind, 'deleted' ); }
        $id = absint( $_POST['id'] ?? 0 ); $data = self::form_data( $kind );
        if ( $kind === 'assessment' && $data['title'] === '' ) { self::redirect( $kind, 'invalid' ); }
        if ( in_array( $kind, array( 'question', 'answer' ), true ) && $data['content'] === '' ) { self::redirect( $kind, 'invalid' ); }
        if ( $id ) { $wpdb->update( $table, $data, array( 'id' => $id ) ); self::redirect( $kind, 'updated' ); }
        $wpdb->insert( $table, $data ); self::redirect( $kind, 'created' );
    }
    private static function form_data( $kind ) {
        if ( $kind === 'assessment' ) { return array( 'title' => sanitize_text_field( wp_unslash( $_POST['title'] ?? '' ) ), 'description' => wp_kses_post( wp_unslash( $_POST['description'] ?? '' ) ), 'status' => in_array( $_POST['status'] ?? '', array( 'draft', 'publish' ), true ) ? $_POST['status'] : 'draft' ); }
        if ( $kind === 'question' ) { return array( 'assessment_id' => absint( $_POST['assessment_id'] ?? 0 ), 'content' => wp_kses_post( wp_unslash( $_POST['content'] ?? '' ) ), 'sort_order' => absint( $_POST['sort_order'] ?? 0 ), 'status' => in_array( $_POST['status'] ?? '', array( 'draft', 'publish' ), true ) ? $_POST['status'] : 'draft' ); }
        return array( 'question_id' => absint( $_POST['question_id'] ?? 0 ), 'content' => wp_kses_post( wp_unslash( $_POST['content'] ?? '' ) ), 'score' => intval( $_POST['score'] ?? 0 ), 'sort_order' => absint( $_POST['sort_order'] ?? 0 ) );
    }
    private static function redirect( $kind, $notice ) { $pages = array( 'assessment' => 'wp-assessment', 'question' => 'wp-assessment-questions', 'answer' => 'wp-assessment-answers' ); wp_safe_redirect( admin_url( 'admin.php?page=' . $pages[ $kind ] . '&notice=' . $notice ) ); exit; }
    private static function redirect_assessment_detail( $assessment_id, $notice ) { wp_safe_redirect( add_query_arg( array( 'page' => 'wp-assessment', 'edit' => absint( $assessment_id ), 'notice' => sanitize_key( $notice ) ), admin_url( 'admin.php' ) ) ); exit; }
    private static function top( $title, $kind ) { self::guard( $kind, 'view' ); echo '<div class="wrap"><h1 class="wp-heading-inline">' . esc_html( $title ) . '</h1>'; if ( WP_Assessment_Permissions::can_create( $kind ) ) { echo ' <a href="#wp-assessment-form" class="page-title-action">Add new</a>'; } if ( isset( $_GET['notice'] ) ) { echo '<div class="notice notice-success is-dismissible"><p>Item ' . esc_html( sanitize_key( $_GET['notice'] ) ) . '.</p></div>'; } }
    private static function bottom() { echo '</div>'; }
    private static function edit_item( $kind ) { global $wpdb; $id = absint( $_GET['edit'] ?? 0 ); if ( ! $id ) { return null; } $tables = array( 'assessment' => 'assessment', 'question' => 'assessment_questions', 'answer' => 'assessment_answers' ); return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}{$tables[$kind]} WHERE id=%d", $id ), ARRAY_A ); }
    private static function select_options( $table, $label, $selected ) { global $wpdb; $rows = $wpdb->get_results( "SELECT id, $label AS label FROM {$wpdb->prefix}$table ORDER BY id DESC" ); foreach ( $rows as $row ) { printf( '<option value="%d" %s>#%d - %s</option>', $row->id, selected( $selected, $row->id, false ), $row->id, esc_html( wp_strip_all_tags( $row->label ) ) ); } }
    private static function form( $kind, $item = null ) { if ( ! WP_Assessment_Permissions::can_create( $kind ) && ! ( $item && WP_Assessment_Permissions::can_edit( $kind ) ) ) { return; } $item = $item ?: array(); echo '<hr><h2 id="wp-assessment-form">' . ( $item ? 'Edit' : 'Add new' ) . '</h2><form method="post">'; wp_nonce_field( 'wp_assessment_admin_action' ); echo '<input type="hidden" name="wp_assessment_action" value="save"><input type="hidden" name="kind" value="' . esc_attr( $kind ) . '"><input type="hidden" name="id" value="' . absint( $item['id'] ?? 0 ) . '"><table class="form-table"><tbody>';
        if ( $kind === 'assessment' ) { self::input( 'Title', 'title', $item['title'] ?? '' ); echo '<tr><th>Description</th><td><textarea name="description" rows="4" class="large-text">' . esc_textarea( $item['description'] ?? '' ) . '</textarea></td></tr>'; self::status( $item['status'] ?? 'draft' ); }
        if ( $kind === 'question' ) { $assessment_id = $item['assessment_id'] ?? absint( wp_unslash( $_GET['assessment_id'] ?? 0 ) ); echo '<tr><th>Assessment</th><td><select name="assessment_id">'; self::select_options( 'assessment', 'title', $assessment_id ); echo '</select></td></tr>'; self::textarea( 'Content', 'content', $item['content'] ?? '' ); self::input( 'Sort order', 'sort_order', $item['sort_order'] ?? 0, 'number' ); self::status( $item['status'] ?? 'draft' ); }
        if ( $kind === 'answer' ) { $question_id = $item['question_id'] ?? absint( wp_unslash( $_GET['question_id'] ?? 0 ) ); echo '<tr><th>Question</th><td><select name="question_id">'; self::select_options( 'assessment_questions', 'content', $question_id ); echo '</select></td></tr>'; self::textarea( 'Content', 'content', $item['content'] ?? '' ); self::input( 'Score', 'score', $item['score'] ?? 0, 'number' ); self::input( 'Sort order', 'sort_order', $item['sort_order'] ?? 0, 'number' ); }
        echo '</tbody></table><p><button class="button button-primary">Save</button></p></form>';
    }
    private static function input( $label, $name, $value, $type = 'text' ) { echo '<tr><th>' . esc_html( $label ) . '</th><td><input required class="regular-text" type="' . esc_attr( $type ) . '" name="' . esc_attr( $name ) . '" value="' . esc_attr( $value ) . '"></td></tr>'; }
    private static function textarea( $label, $name, $value ) { echo '<tr><th>' . esc_html( $label ) . '</th><td><textarea required name="' . esc_attr( $name ) . '" rows="4" class="large-text">' . esc_textarea( $value ) . '</textarea></td></tr>'; }
    private static function status( $value ) { echo '<tr><th>Status</th><td><select name="status"><option value="draft" ' . selected( $value, 'draft', false ) . '>Draft</option><option value="publish" ' . selected( $value, 'publish', false ) . '>Publish</option></select></td></tr>'; }
    private static function actions( $kind, $id, $show_edit = true ) { $page = array( 'assessment' => 'wp-assessment', 'question' => 'wp-assessment-questions', 'answer' => 'wp-assessment-answers' )[ $kind ]; echo $show_edit && WP_Assessment_Permissions::can_edit( $kind ) ? '<a href="' . esc_url( admin_url( 'admin.php?page=' . $page . '&edit=' . $id ) ) . '">Edit</a> ' : ''; if ( WP_Assessment_Permissions::can_delete( $kind ) ) { echo '<form method="post" style="display:inline">'; wp_nonce_field( 'wp_assessment_admin_action' ); echo '<input type="hidden" name="wp_assessment_action" value="delete"><input type="hidden" name="kind" value="' . esc_attr( $kind ) . '"><input type="hidden" name="id" value="' . absint( $id ) . '"><button class="button-link-delete" onclick="return confirm(\'Delete this item and child data?\')">Delete</button></form>'; } }
    private static function render_question_modal( $assessment_id, $question, $answers ) {
        $modal_id = 'wp-assessment-question-modal-' . absint( $question->id ); $save_id = 'wp-assessment-question-save-' . absint( $question->id ); $tbody_id = 'wp-assessment-answer-list-' . absint( $question->id ); $template_id = 'wp-assessment-answer-template-' . absint( $question->id ); $can_edit_answers = WP_Assessment_Permissions::can_edit( 'answer' ); $can_create_answers = WP_Assessment_Permissions::can_create( 'answer' );
        echo '<div id="' . esc_attr( $modal_id ) . '" class="wp-assessment-modal" hidden><div class="wp-assessment-modal__content" role="dialog" aria-modal="true" aria-labelledby="' . esc_attr( $modal_id ) . '-title"><div class="wp-assessment-modal__header"><h2 id="' . esc_attr( $modal_id ) . '-title">Edit Question</h2><button type="button" class="button wp-assessment-modal-close">Close</button></div><form method="post">';
        wp_nonce_field( 'wp_assessment_admin_action' );
        echo '<input type="hidden" name="wp_assessment_action" value="save_question_detail"><input type="hidden" name="kind" value="question"><input type="hidden" name="assessment_id" value="' . absint( $assessment_id ) . '"><input type="hidden" name="id" value="' . absint( $question->id ) . '"><p><label><strong>Question</strong><textarea name="content" required>' . esc_textarea( $question->content ) . '</textarea></label></p><p><label><strong>Status </strong><select name="status"><option value="draft" ' . selected( $question->status, 'draft', false ) . '>Draft</option><option value="publish" ' . selected( $question->status, 'publish', false ) . '>Publish</option></select></label></p><h3>Answers</h3>';
        echo '<table class="widefat striped"><thead><tr>' . ( $can_edit_answers || $can_create_answers ? '<th>Order</th>' : '' ) . '<th>Answer</th><th>Author</th><th>Answered at</th>' . ( $can_edit_answers ? '<th>Actions</th>' : '' ) . '</tr></thead><tbody id="' . esc_attr( $tbody_id ) . '" data-wp-assessment-sortable data-save-button="#' . esc_attr( $save_id ) . '">'; foreach ( $answers as $answer ) { echo '<tr' . ( $can_edit_answers ? ' draggable="true"' : '' ) . '>'; if ( $can_edit_answers ) { echo '<td><span class="dashicons dashicons-menu wp-assessment-drag-handle"></span><input type="hidden" name="answer_order[]" value="' . absint( $answer->id ) . '"></td>'; } elseif ( $can_create_answers ) { echo '<td></td>'; } echo '<td><span class="wp-assessment-answer-display">' . esc_html( wp_strip_all_tags( $answer->content ) ) . '</span>'; if ( $can_edit_answers ) { echo '<textarea hidden name="answers[' . absint( $answer->id ) . '][content]" required>' . esc_textarea( $answer->content ) . '</textarea>'; } echo '</td><td>' . esc_html( $answer->author_name ?: 'System' ) . '</td><td>' . esc_html( $answer->created_at ) . '</td>'; if ( $can_edit_answers ) { echo '<td><button type="button" class="button-link wp-assessment-edit-answer" onclick="var row=this.closest(\'tr\');row.querySelector(\'.wp-assessment-answer-display\').hidden=true;var field=row.querySelector(\'textarea\');field.hidden=false;field.focus();this.hidden=true">Edit</button> <button type="button" class="button-link-delete" onclick="var input=document.createElement(\'input\');input.type=\'hidden\';input.name=\'delete_answers[]\';input.value=\'' . absint( $answer->id ) . '\';this.closest(\'form\').appendChild(input);this.closest(\'tr\').remove()">Delete</button></td>'; } echo '</tr>'; } echo '</tbody></table>';
        if ( $can_create_answers ) { echo '<p><button type="button" class="button" onclick="var template=document.getElementById(\'' . esc_attr( $template_id ) . '\');var target=document.getElementById(\'' . esc_attr( $tbody_id ) . '\');if(template&&target){target.insertAdjacentHTML(\'beforeend\',template.innerHTML)}">Add answer</button></p><template id="' . esc_attr( $template_id ) . '"><tr><td><span class="dashicons dashicons-menu wp-assessment-drag-handle"></span></td><td><textarea name="new_answers[][content]" required></textarea></td><td>Current user</td><td>Not saved</td><td><button type="button" class="button-link-delete" onclick="this.closest(\'tr\').remove()">Delete</button></td></tr></template>'; }
        echo '<p><button id="' . esc_attr( $save_id ) . '" class="button button-primary">Save changes</button></p></form></div></div>';
    }
    private static function render_assessment_detail( $assessment ) {
        global $wpdb; $assessment_id = absint( $assessment['id'] ); $question_table = $wpdb->prefix . 'assessment_questions'; $answer_table = $wpdb->prefix . 'assessment_answers';
        $questions = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM $question_table WHERE assessment_id = %d ORDER BY sort_order ASC, id ASC", $assessment_id ) );
        $answer_rows = $wpdb->get_results( $wpdb->prepare( "SELECT r.*, u.display_name AS author_name FROM $answer_table r LEFT JOIN {$wpdb->users} u ON u.ID = r.user_id WHERE r.question_id IN (SELECT id FROM $question_table WHERE assessment_id = %d) ORDER BY r.question_id, r.sort_order ASC, r.id ASC", $assessment_id ) ); $answers_by_question = array(); foreach ( $answer_rows as $answer ) { $answers_by_question[ $answer->question_id ][] = $answer; }
        $back_url = admin_url( 'admin.php?page=wp-assessment' ); $add_question_url = add_query_arg( array( 'page' => 'wp-assessment-questions', 'assessment_id' => $assessment_id ), admin_url( 'admin.php' ) ) . '#wp-assessment-form'; $can_reorder = WP_Assessment_Permissions::can_edit( 'question' );
        echo '<p><a href="' . esc_url( $back_url ) . '">&larr; Back to Assessments</a></p><h2>Edit Assessment: ' . esc_html( $assessment['title'] ) . '</h2>'; self::form( 'assessment', $assessment ); echo '<hr><h2>Questions</h2>';
        if ( WP_Assessment_Permissions::can_create( 'question' ) ) { echo '<p><a class="button button-primary" href="' . esc_url( $add_question_url ) . '">Add question</a></p>'; }
        if ( ! $questions ) { echo '<p>No questions have been added to this assessment.</p>'; return; }
        if ( $can_reorder ) { echo '<p>Drag questions to set their display order, then save your changes.</p><form id="wp-assessment-question-order-form" method="post">'; wp_nonce_field( 'wp_assessment_admin_action' ); echo '<input type="hidden" name="wp_assessment_action" value="reorder_questions"><input type="hidden" name="kind" value="question"><input type="hidden" name="assessment_id" value="' . $assessment_id . '"></form>'; }
        echo '<table class="widefat striped"><thead><tr>' . ( $can_reorder ? '<th>Order</th>' : '' ) . '<th>ID</th><th>Question</th><th>Status</th><th>Actions</th></tr></thead><tbody data-wp-assessment-sortable data-save-button="#wp-assessment-save-question-order">';
        foreach ( $questions as $question ) { $modal_id = 'wp-assessment-question-modal-' . absint( $question->id ); $add_answer_url = add_query_arg( array( 'page' => 'wp-assessment-answers', 'question_id' => absint( $question->id ) ), admin_url( 'admin.php' ) ) . '#wp-assessment-form'; echo '<tr' . ( $can_reorder ? ' draggable="true"' : '' ) . '>'; if ( $can_reorder ) { echo '<td><span class="dashicons dashicons-menu wp-assessment-drag-handle"></span><input type="hidden" form="wp-assessment-question-order-form" name="order[]" value="' . absint( $question->id ) . '"></td>'; } echo '<td>' . absint( $question->id ) . '</td><td>' . esc_html( wp_trim_words( wp_strip_all_tags( $question->content ), 16 ) ) . '</td><td>' . esc_html( $question->status ) . '</td><td>'; if ( WP_Assessment_Permissions::can_edit( 'question' ) ) { echo '<button type="button" class="button-link wp-assessment-open-question" data-modal="' . esc_attr( $modal_id ) . '">Edit</button> '; } self::actions( 'question', $question->id, false ); if ( WP_Assessment_Permissions::can_create( 'answer' ) ) { echo '<a href="' . esc_url( $add_answer_url ) . '">Add answer</a>'; } echo '</td></tr>'; }
        echo '</tbody></table>'; if ( $can_reorder ) { echo '<p><button id="wp-assessment-save-question-order" type="submit" form="wp-assessment-question-order-form" class="button button-primary" disabled>Save question order</button></p>'; }
        foreach ( $questions as $question ) { self::render_question_modal( $assessment_id, $question, $answers_by_question[ $question->id ] ?? array() ); }
    }
    public static function render_assessments() {
        global $wpdb;
        self::top( 'Assessments', 'assessment' );
        $edited = self::edit_item( 'assessment' );
        if ( $edited ) { self::render_assessment_detail( $edited ); self::bottom(); return; }
        $can_reorder = WP_Assessment_Permissions::can_edit( 'assessment' );
        $rows = $wpdb->get_results( "SELECT * FROM {$wpdb->prefix}assessment ORDER BY sort_order ASC, id DESC" );
        if ( $can_reorder ) {
            echo '<p>Drag rows by the handle to set the display order, then save your changes.</p><form id="wp-assessment-order-form" method="post">';
            wp_nonce_field( 'wp_assessment_admin_action' );
            echo '<input type="hidden" name="wp_assessment_action" value="reorder"><input type="hidden" name="kind" value="assessment"></form>';
        }
        echo '<table class="widefat striped"><thead><tr>' . ( $can_reorder ? '<th scope="col">Order</th>' : '' ) . '<th>ID</th><th>Title</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody id="wp-assessment-sortable">';
        foreach ( $rows as $row ) {
            echo '<tr' . ( $can_reorder ? ' draggable="true"' : '' ) . '>';
            if ( $can_reorder ) { echo '<td><span class="dashicons dashicons-menu wp-assessment-drag-handle" aria-hidden="true"></span><input type="hidden" form="wp-assessment-order-form" name="order[]" value="' . absint( $row->id ) . '"></td>'; }
            echo '<td>' . absint( $row->id ) . '</td><td>' . esc_html( $row->title ) . '</td><td>' . esc_html( $row->status ) . '</td><td>' . esc_html( $row->updated_at ) . '</td><td>';
            self::actions( 'assessment', $row->id );
            echo '</td></tr>';
        }
        echo '</tbody></table>';
        if ( $can_reorder ) { echo '<p><button id="wp-assessment-save-order" type="submit" form="wp-assessment-order-form" class="button button-primary" disabled>Save order</button></p>'; }
        self::form( 'assessment' );
        self::bottom();
    }
    public static function render_questions() { global $wpdb; self::top( 'Questions', 'question' ); $rows = $wpdb->get_results( "SELECT q.*, a.title FROM {$wpdb->prefix}assessment_questions q LEFT JOIN {$wpdb->prefix}assessment a ON q.assessment_id=a.id ORDER BY q.assessment_id, q.sort_order, q.id" ); echo '<table class="widefat striped"><thead><tr><th>ID</th><th>Assessment</th><th>Question</th><th>Status</th><th>Order</th><th>Actions</th></tr></thead><tbody>'; foreach ( $rows as $row ) { echo '<tr><td>' . $row->id . '</td><td>' . esc_html( $row->title ) . '</td><td>' . esc_html( wp_trim_words( wp_strip_all_tags( $row->content ), 12 ) ) . '</td><td>' . esc_html( $row->status ) . '</td><td>' . $row->sort_order . '</td><td>'; self::actions( 'question', $row->id ); echo '</td></tr>'; } echo '</tbody></table>'; self::form( 'question', self::edit_item( 'question' ) ); self::bottom(); }
    public static function render_answers() { global $wpdb; self::top( 'Answers', 'answer' ); $rows = $wpdb->get_results( "SELECT r.*, q.content question FROM {$wpdb->prefix}assessment_answers r LEFT JOIN {$wpdb->prefix}assessment_questions q ON r.question_id=q.id ORDER BY r.question_id, r.sort_order, r.id" ); echo '<table class="widefat striped"><thead><tr><th>ID</th><th>Question</th><th>Answer</th><th>Score</th><th>Order</th><th>Actions</th></tr></thead><tbody>'; foreach ( $rows as $row ) { echo '<tr><td>' . $row->id . '</td><td>' . esc_html( wp_trim_words( wp_strip_all_tags( $row->question ), 8 ) ) . '</td><td>' . esc_html( wp_trim_words( wp_strip_all_tags( $row->content ), 12 ) ) . '</td><td>' . $row->score . '</td><td>' . $row->sort_order . '</td><td>'; self::actions( 'answer', $row->id ); echo '</td></tr>'; } echo '</tbody></table>'; self::form( 'answer', self::edit_item( 'answer' ) ); self::bottom(); }
    public static function render_permissions() { if ( ! WP_Assessment_Permissions::can_manage_permissions() ) { wp_die( 'You do not have permission to manage role permissions.' ); } if ( isset( $_POST['wp_assessment_permissions_nonce'] ) && wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['wp_assessment_permissions_nonce'] ) ), 'wp_assessment_permissions' ) ) { $submitted = (array) wp_unslash( $_POST['permissions'] ?? array() ); $permissions = array(); foreach ( wp_roles()->roles as $role_key => $role_data ) { if ( in_array( $role_key, array( 'administrator', 'assessment_manager' ), true ) ) { continue; } foreach ( WP_Assessment_Permissions::all_permission_keys() as $permission ) { $permissions[ $role_key ][ $permission ] = ! empty( $submitted[ $role_key ][ $permission ] ); } } update_option( WP_ASSESSMENT_PERMISSION_OPTION, $permissions, false ); WP_Assessment_Permissions::sync_role_capabilities( $permissions ); echo '<div class="notice notice-success"><p>Permissions saved.</p></div>'; } $permissions = WP_Assessment_Permissions::permissions(); echo '<div class="wrap"><h1>Mini Assessment - Role permissions</h1><p>Each row is one permission. Each column is an existing WordPress role. Assessment Manager and Administrator always have full access.</p><form method="post">'; wp_nonce_field( 'wp_assessment_permissions', 'wp_assessment_permissions_nonce' ); echo '<table class="widefat striped"><thead><tr><th>Permission</th>'; foreach ( wp_roles()->roles as $role_key => $role_data ) { echo '<th>' . esc_html( translate_user_role( $role_data['name'] ) ) . '</th>'; } echo '</tr></thead><tbody>'; foreach ( WP_Assessment_Permissions::entities() as $entity => $entity_label ) { foreach ( WP_Assessment_Permissions::actions() as $action ) { $permission = WP_Assessment_Permissions::permission_key( $entity, $action ); echo '<tr><td><strong>' . esc_html( $entity_label ) . '</strong> - ' . esc_html( ucfirst( $action ) ) . '</td>'; foreach ( wp_roles()->roles as $role_key => $role_data ) { if ( in_array( $role_key, array( 'administrator', 'assessment_manager' ), true ) ) { echo '<td><strong>Full</strong></td>'; } else { printf( '<td><input type="checkbox" name="permissions[%s][%s]" value="1" %s></td>', esc_attr( $role_key ), esc_attr( $permission ), checked( ! empty( $permissions[ $role_key ][ $permission ] ), true, false ) ); } } echo '</tr>'; } } echo '</tbody></table><p class="submit"><button class="button button-primary">Save permissions</button></p></form></div>'; }
}
add_action( 'admin_init', array( 'WP_Assessment_Admin', 'handle_actions' ) );
add_action( 'admin_enqueue_scripts', array( 'WP_Assessment_Admin', 'enqueue_assets' ) );
