<?php
class WP_Assessment_JWT_Auth extends WP_REST_Controller {
    protected $namespace = 'assessment/v1';
    public function register_routes() { register_rest_route( $this->namespace, '/auth/login', array( 'methods' => WP_REST_Server::CREATABLE, 'callback' => array( $this, 'login' ), 'permission_callback' => '__return_true' ) ); register_rest_route( $this->namespace, '/auth/refresh', array( 'methods' => WP_REST_Server::CREATABLE, 'callback' => array( $this, 'refresh' ), 'permission_callback' => '__return_true' ) ); register_rest_route( $this->namespace, '/auth/logout', array( 'methods' => WP_REST_Server::CREATABLE, 'callback' => array( $this, 'logout' ), 'permission_callback' => '__return_true' ) ); register_rest_route( $this->namespace, '/auth/me', array( 'methods' => WP_REST_Server::READABLE, 'callback' => array( $this, 'me' ), 'permission_callback' => array( $this, 'authenticated' ) ) ); }
    private function secret() { return defined( 'AUTH_KEY' ) ? AUTH_KEY : wp_salt( 'auth' ); }
    private function encode( $data ) { return rtrim( strtr( base64_encode( $data ), '+/', '-_' ), '=' ); }
    private function decode( $data ) { return base64_decode( strtr( $data, '-_', '+/' ) ); }
    private function token( $user_id, $type, $ttl, $jti = '' ) { $header = $this->encode( wp_json_encode( array( 'alg' => 'HS256', 'typ' => 'JWT' ) ) ); $payload = $this->encode( wp_json_encode( array( 'iss' => get_bloginfo( 'url' ), 'sub' => (int) $user_id, 'typ' => $type, 'jti' => $jti, 'iat' => time(), 'exp' => time() + $ttl ) ) ); return $header . '.' . $payload . '.' . $this->encode( hash_hmac( 'sha256', $header . '.' . $payload, $this->secret(), true ) ); }
    public function issue_token( $user_id ) { return $this->token( $user_id, 'access', (int) apply_filters( 'wp_assessment_jwt_ttl', 15 * MINUTE_IN_SECONDS ) ); }
    private function verify( $token, $type ) { $parts = explode( '.', (string) $token ); if ( count( $parts ) !== 3 ) { return new WP_Error( 'jwt_invalid', 'Authentication token is invalid.', array( 'status' => 401 ) ); } $expected = $this->encode( hash_hmac( 'sha256', $parts[0] . '.' . $parts[1], $this->secret(), true ) ); $payload = json_decode( $this->decode( $parts[1] ), true ); if ( ! hash_equals( $expected, $parts[2] ) || ! is_array( $payload ) || empty( $payload['sub'] ) || empty( $payload['exp'] ) || $payload['exp'] < time() || ( $payload['typ'] ?? '' ) !== $type ) { return new WP_Error( 'jwt_invalid', 'Authentication token is invalid or expired.', array( 'status' => 401 ) ); } return $payload; }
    private function cookie( $value = '', $expires = 0 ) { setcookie( 'wp_assessment_refresh', $value, array( 'expires' => $expires, 'path' => '/wp-json/assessment/v1/auth', 'domain' => '', 'secure' => is_ssl(), 'httponly' => true, 'samesite' => 'Lax' ) ); }
    private function issue_refresh( $user_id ) { $jti = wp_generate_password( 48, false, false ); update_user_meta( $user_id, 'wp_assessment_refresh_' . $jti, wp_hash( $jti ) ); $ttl = (int) apply_filters( 'wp_assessment_refresh_ttl', 7 * DAY_IN_SECONDS ); $this->cookie( $this->token( $user_id, 'refresh', $ttl, $jti ), time() + $ttl ); }
    public function authenticate_request() { $header = isset( $_SERVER['HTTP_AUTHORIZATION'] ) ? trim( $_SERVER['HTTP_AUTHORIZATION'] ) : ''; if ( ! preg_match( '/^Bearer\s+(.+)$/i', $header, $matches ) ) { return new WP_Error( 'jwt_missing', 'Authentication token is required.', array( 'status' => 401 ) ); } $payload = $this->verify( $matches[1], 'access' ); if ( is_wp_error( $payload ) ) { return $payload; } $user = get_user_by( 'id', (int) $payload['sub'] ); if ( ! $user || ! $user->exists() ) { return new WP_Error( 'jwt_invalid', 'Authentication token is invalid.', array( 'status' => 401 ) ); } wp_set_current_user( $user->ID ); return $user; }
    public function authenticated() { $user = $this->authenticate_request(); return is_wp_error( $user ) ? $user : true; }
    public function login( $request ) { $username = sanitize_user( (string) $request->get_param( 'username' ) ); $password = (string) $request->get_param( 'password' ); if ( $username === '' || $password === '' ) { return new WP_Error( 'invalid_credentials', 'Invalid username or password.', array( 'status' => 401 ) ); } $user = wp_authenticate( $username, $password ); if ( is_wp_error( $user ) ) { return new WP_Error( 'invalid_credentials', 'Invalid username or password.', array( 'status' => 401 ) ); } $this->issue_refresh( $user->ID ); return rest_ensure_response( array( 'token' => $this->issue_token( $user->ID ), 'user' => $this->user_data( $user ) ) ); }
    public function refresh() { $payload = $this->verify( $_COOKIE['wp_assessment_refresh'] ?? '', 'refresh' ); $stored = ! is_wp_error( $payload ) && ! empty( $payload['jti'] ) ? get_user_meta( (int) $payload['sub'], 'wp_assessment_refresh_' . $payload['jti'], true ) : ''; if ( is_wp_error( $payload ) || ! $stored || ! hash_equals( $stored, wp_hash( $payload['jti'] ) ) ) { $this->cookie(); return new WP_Error( 'refresh_invalid', 'Refresh session is invalid.', array( 'status' => 401 ) ); } delete_user_meta( (int) $payload['sub'], 'wp_assessment_refresh_' . $payload['jti'] ); $this->issue_refresh( (int) $payload['sub'] ); return rest_ensure_response( array( 'token' => $this->issue_token( (int) $payload['sub'] ) ) ); }
    public function logout() { $payload = $this->verify( $_COOKIE['wp_assessment_refresh'] ?? '', 'refresh' ); if ( ! is_wp_error( $payload ) && ! empty( $payload['jti'] ) ) { delete_user_meta( (int) $payload['sub'], 'wp_assessment_refresh_' . $payload['jti'] ); } $this->cookie(); return rest_ensure_response( array( 'logged_out' => true ) ); }
    private function user_data( $user ) { $actions = array(); foreach ( array( 'assessment', 'question', 'answer' ) as $entity ) { $actions[ $entity ] = array( 'create' => WP_Assessment_Permissions::can( $entity, 'create' ), 'edit' => WP_Assessment_Permissions::can( $entity, 'edit' ), 'delete' => WP_Assessment_Permissions::can( $entity, 'delete' ) ); } return array( 'id' => (int) $user->ID, 'username' => $user->user_login, 'display_name' => $user->display_name, 'roles' => array_values( $user->roles ), 'permissions' => array( 'manager' => WP_Assessment_Permissions::can_manage_content(), 'assessment' => $actions['assessment']['create'], 'question' => $actions['question']['create'], 'answer' => $actions['answer']['create'], 'actions' => $actions ) ); }
    public function me() { return rest_ensure_response( $this->user_data( wp_get_current_user() ) ); }
}
